/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/alfredoso/GitHub/TesisCuadricoptero/EstacionControl_ROS/src/comunicacion_serial/msg/ComandoEncendido.msg
 *
 */


#ifndef COMUNICACION_SERIAL_MESSAGE_COMANDOENCENDIDO_H
#define COMUNICACION_SERIAL_MESSAGE_COMANDOENCENDIDO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comunicacion_serial
{
template <class ContainerAllocator>
struct ComandoEncendido_
{
  typedef ComandoEncendido_<ContainerAllocator> Type;

  ComandoEncendido_()
    : encendido(0)  {
    }
  ComandoEncendido_(const ContainerAllocator& _alloc)
    : encendido(0)  {
    }



   typedef uint8_t _encendido_type;
  _encendido_type encendido;




  typedef boost::shared_ptr< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> const> ConstPtr;

}; // struct ComandoEncendido_

typedef ::comunicacion_serial::ComandoEncendido_<std::allocator<void> > ComandoEncendido;

typedef boost::shared_ptr< ::comunicacion_serial::ComandoEncendido > ComandoEncendidoPtr;
typedef boost::shared_ptr< ::comunicacion_serial::ComandoEncendido const> ComandoEncendidoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace comunicacion_serial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'comunicacion_serial': ['/home/alfredoso/GitHub/TesisCuadricoptero/EstacionControl_ROS/src/comunicacion_serial/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca1bb7756711dc79b7b20ec735aada07";
  }

  static const char* value(const ::comunicacion_serial::ComandoEncendido_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca1bb7756711dc79ULL;
  static const uint64_t static_value2 = 0xb7b20ec735aada07ULL;
};

template<class ContainerAllocator>
struct DataType< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comunicacion_serial/ComandoEncendido";
  }

  static const char* value(const ::comunicacion_serial::ComandoEncendido_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 encendido\n\
";
  }

  static const char* value(const ::comunicacion_serial::ComandoEncendido_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.encendido);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ComandoEncendido_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comunicacion_serial::ComandoEncendido_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comunicacion_serial::ComandoEncendido_<ContainerAllocator>& v)
  {
    s << indent << "encendido: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.encendido);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMUNICACION_SERIAL_MESSAGE_COMANDOENCENDIDO_H
